### ISSUE TITLE
Undefined symbol in Manjaro installation

### ISSUE THREAD

**Issue by ccuetom** [devitocodes/pyrevolve#59]
We have been having some issues with installing pyrevolve in Manjaro. The pip installation completes as expected, but then the import throws the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/oab18/anaconda3/envs/stride/lib/python3.10/site-packages/pyrevolve/__init__.py", line 3, in <module>
    from pyrevolve.pyrevolve import * # noqa
  File "/home/oab18/anaconda3/envs/stride/lib/python3.10/site-packages/pyrevolve/pyrevolve.py", line 6, in <module>
    from . import crevolve as cr
ImportError: /home/oab18/anaconda3/envs/stride/lib/python3.10/site-packages/pyrevolve/crevolve.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE
```

This was done in a fresh anaconda environment with Python 3.10.5. We are still investigating the issue, but any ideas on what could be causing this?

**Comment by navjotk** [comment]
To me this seems like a compiler issue: e.g. some dynamic libraries were loaded at the time of installation and are no longer on "LD_LIBRARY_PATH". Did you have any success?
